// Generated by https://quicktype.io

export interface IndicatorDB {
  Dolares: Indicator[];
  Euros: Indicator[];
  IPCs: Indicator[];
  UFs: Indicator[];
  UTMs: Indicator[];
}

export interface Indicator {
  Valor: string;
  Fecha: string;
}
